services:

    php-fpm:

        image: trafex/php-nginx:latest

        container_name: docker-cake-2-webserver

        working_dir: /app

        volumes:

            - ./:/app

        environment:

            - WEB_DOCUMENT_ROOT=/app/webroot

        ports:

            - "8082:80"

    mysql:

        image: mysql:latest

        container_name: docker-cake-2-mysql

        working_dir: /app

        volumes:

            - .:/app

            - ./tmp/data/mysql_db:/var/lib/mysql

        env_file:

            - mysql.env

        command: mysqld --character-set-server=utf8 --init-connect='SET NAMES UTF8;'

        ports:

            - "4307:3306"


